# A developer environment for TypeScript/Node.js, 
services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: sleep infinity
    networks:
      - default
