#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
# This section orchestrates host actions and explicit guest SSH commands. The
# reusable wizard library above handles prompts; secrets are entered in guest CLIs.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VM="$SCRIPT_DIR/../scripts/vm.sh"
[[ -t 0 && -t 1 ]] || { printf '%sRun setup in an interactive host terminal.%s\n' "$RED" "$RESET" >&2; exit 1; }
"$VM" doctor
banner "Open Collective development VM"

stage "Optional host SSH agent forwarding"
say "Setup can use an already loaded host agent after your explicit approval."
say "It never creates keys, starts an agent, or loads or removes identities."
say "Without authentication, public repositories use HTTPS and Git pushes are unavailable."
"$VM" ssh-forwarding

stage "VM and shared SSH entry"
"$VM" up
say "The oc-dev SSH entry is now available to SSH, Orca, and VS Code."
say "Host key checking remembers this VM; an unexpected change will be rejected."

# Public repositories remain usable without credentials. The guest records
# actual GitHub/private-repository access for this wizard's deferred-work summary.
stage "Guest Git identity and repositories"
"$VM" guest bash /opt/oc-vm/guest-onboarding.sh git
git_status=$("$VM" ssh node /opt/oc-vm/guest.mjs git-status)
case "$git_status" in
  https-public)
    SKIPPED+=("Git pushes need separate authentication; public repositories were initialized over HTTPS.")
    SKIPPED+=("Private opencollective-security access is unavailable; its initialization was skipped.")
    ;;
  ssh-public)
    SKIPPED+=("Private opencollective-security access is unavailable; its initialization was skipped.")
    ;;
  ssh-private) ;;
  *) echo 'Unexpected guest Git access report' >&2; exit 1 ;;
esac

# Optional provider logins may be deferred or fail without blocking stack setup.
# Each deferred command is recorded in SKIPPED for the final resumable checklist.
stage "GitHub CLI login (guest)"
say "Git SSH access uses the forwarded agent; gh API access requires a separate guest credential."
say "The web flow requests GitHub CLI's default repo/read:org/gist permissions."
say "Its credential stays inside this VM; no host GitHub token is copied."
if confirm "Configure GitHub CLI now?"; then
  if ! "$VM" guest gh auth login --hostname github.com --git-protocol ssh --skip-ssh-key --web; then
    SKIPPED+=("GitHub CLI login failed; retry later with ./scripts/vm.sh guest gh auth login --hostname github.com --git-protocol ssh --skip-ssh-key --web")
  fi
else
  SKIPPED+=("Guest gh login: ./scripts/vm.sh guest gh auth login --hostname github.com --git-protocol ssh --skip-ssh-key --web")
fi

stage "Codex login (guest)"
say "Use the one-time device code in your host browser; credentials are stored only in the VM."
open_url "https://chatgpt.com/#settings/Security"
step "Enable device-code login if needed, then follow the URL and code printed by Codex."
if confirm "Sign in to Codex now?"; then
  if ! "$VM" guest codex login --device-auth; then
    SKIPPED+=("Codex login failed; retry later with ./scripts/vm.sh guest codex login --device-auth")
  fi
else
  SKIPPED+=("Codex: ./scripts/vm.sh guest codex login --device-auth")
fi

stage "OpenCode provider login (guest)"
say "Choose your provider in OpenCode and follow its sign-in or API-key prompts."
say "Enter any API key only in the guest login prompt."
if confirm "Configure an OpenCode provider now?"; then
  if ! "$VM" guest opencode auth login; then
    SKIPPED+=("OpenCode login failed; retry later with ./scripts/vm.sh guest opencode auth login")
  fi
else
  SKIPPED+=("OpenCode: ./scripts/vm.sh guest opencode auth login")
fi

# Unlike optional logins, bootstrap failures stop the wizard. The guest helper
# preserves existing configuration/data and can be rerun after fixing the cause.
stage "Development stack"
"$VM" guest node /opt/oc-vm/guest.mjs stack
"$VM" guest node /opt/oc-vm/guest.mjs doctor
say "Connect with ssh oc-dev, cd /workspace, and run: run frontend api"
say "In Orca Settings -> SSH, import oc-dev and select /workspace as the remote project location."
say "For service worktrees, add the service repository as its own Orca project."
say "In VS Code Remote-SSH, connect to oc-dev and open /workspace."
finish
